In [2]:
import numpy as np

In [3]:
A = np.array([[23,50,19],
             [7,12,109],
             [57,67,98],
             ])
A
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

### Cara 1 membuat Tensor

In [20]:
M1 = np.array([[23, 50],
               [7, 12]])
M2 = np.array([[57, 67],
               [99, 43]])
M3 = np.array([[75, 21],
               [57, 12]])
M4 = np.array([[87, 26],
               [18, 84]])

In [21]:
tensor = np.array([M1, M2, M3, M4])
tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

### Cara 2 membuat Tensor dengan mengetik Manual

In [34]:
x = np.array([
            [[23,50], 
             [7,12]],
            [[57,67],
              [99,43]],
            [[75,21],
             [57,12]],
            [[87,26],
             [18,84]]
             ])
x.shape

(4, 2, 2)

### Perkalian Matrix

In [38]:
# Define matrix A
A = np.array([
    [23,50,19],
    [7,12,109],
    [57,67,98],
])
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [43]:
# Define matrix B
B = np.array([17,22,19])

In [41]:
# Perkalian Matrix dengan Numpy
np.dot(A,B)

array([1852, 2454, 4305])

In [42]:
# Perkalian matrix dengan @
A @ B

array([1852, 2454, 4305])

### Melakukan Transpose, hitung determinan, dan inverse

In [59]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [44]:
# Transpose matrix A
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [51]:
# Menghitung determinan matrix A
np.round(np.linalg.det(A))
# Jika ada determinan artinya bisa di jadikan inverse, jika tidak maka tidak bisa

131344.0

In [54]:
# Menghitung Matrix invers 
A_inv = np.linalg.inv(A)
A_inv

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])

In [62]:
# Melakukan perkalian invers matrix terhadap matrix aslinya akan membuat matrix identitas
C = A @ A_inv
# Jika matrix identitas dikali dengan matrix aslinya maka hasilnya akan menjadi matrix aslinya dan bersifat komutatif
A @ C

array([[ 23.,  50.,  19.],
       [  7.,  12., 109.],
       [ 57.,  67.,  98.]])