In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
A[1, :]

array([4, 5, 6])

In [4]:
A[:, -1]

array([3, 6, 9])

In [5]:
A[2, 1:]

array([8, 9])

In [6]:
M = np.array([[1, 3],
              [3, 2]])

M

array([[1, 3],
       [3, 2]])

In [7]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [8]:
M @ I

array([[1., 3.],
       [3., 2.]])

In [9]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.diag(np.array([1, 2, 3]))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [11]:
np.diag(np.diag(A))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [12]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
B = np.array([[2, 2, 1],
              [1, 3, 1],
              [2, 0, 1]])
B

array([[2, 2, 1],
       [1, 3, 1],
       [2, 0, 1]])

In [14]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## **Operasi Aritmatika**

### **penjumlahan**

In [15]:
# matrix terhadap skalar
10 + A

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [16]:
# matrix terhadap matrix
A + B

array([[ 3,  4,  4],
       [ 5,  8,  7],
       [ 9,  8, 10]])

In [17]:
v = np.array([2, 1, 3, 5])
v

array([2, 1, 3, 5])

In [18]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
# error shape vector tidak sama dengan jumlah kolom matrix
A + v

ValueError: operands could not be broadcast together with shapes (3,3) (4,) 

### **pengurangan**

In [20]:
B

array([[2, 2, 1],
       [1, 3, 1],
       [2, 0, 1]])

In [21]:
# matrix terhadap skalar
B - 1

array([[ 1,  1,  0],
       [ 0,  2,  0],
       [ 1, -1,  0]])

In [22]:
# matrix terhadap matrix
A - B

array([[-1,  0,  2],
       [ 3,  2,  5],
       [ 5,  8,  8]])

### **pembagian**

In [23]:
# matrix terhadap scalar
A / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [24]:
# matrix terhadap matrix
A / B

C:\Users\alexa\AppData\Local\Temp\ipykernel_9764\2724318927.py:2: RuntimeWarning: divide by zero encountered in true_divide
  A / B


array([[0.5       , 1.        , 3.        ],
       [4.        , 1.66666667, 6.        ],
       [3.5       ,        inf, 9.        ]])

### **perkalian**

In [25]:
# matrix terhadap scalar
A * 10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [26]:
# hadamard product (element-wise multiplication)
A * B

array([[ 2,  4,  3],
       [ 4, 15,  6],
       [14,  0,  9]])

In [27]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
B

array([[2, 2, 1],
       [1, 3, 1],
       [2, 0, 1]])

In [29]:
# matrix-matrix multiplication
A @ B

array([[10,  8,  6],
       [25, 23, 15],
       [40, 38, 24]])

In [30]:
# tidak komutatif
B @ A

array([[17, 22, 27],
       [20, 25, 30],
       [ 9, 12, 15]])

In [31]:
C = np.array([[2, 1, 5], 
              [5, 0, 2],
              [1, 1, 0],
              [2, 0, 1]])
C

array([[2, 1, 5],
       [5, 0, 2],
       [1, 1, 0],
       [2, 0, 1]])

In [32]:
# error shape tidak sesuai aturan
A @ C

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [33]:
C @ A

array([[41, 49, 57],
       [19, 26, 33],
       [ 5,  7,  9],
       [ 9, 12, 15]])

## **Transpose**

In [ ]:
A

In [ ]:
A.T

## **Inverse**

In [ ]:
B

In [ ]:
B_inv = np.linalg.inv(B)
B_inv

In [ ]:
B @ B_inv

In [ ]:
A

In [ ]:
np.linalg.inv(A)

In [ ]:
F = np.array([[1, 1, 1],
             [2, 2, 2],
             [2, 1, 0]])
F

In [ ]:
np.linalg.inv(F)

## **Determinant**

In [ ]:
G = np.array([[1, 3],
             [3, 2]])
G

In [ ]:
contoh = np.linalg.det(G)
contoh

In [ ]:
# membulatkan
np.round(contoh)

In [ ]:
np.linalg.det(A)

In [ ]:
K = np.array([[1,2],
              [2,4]])
K

In [ ]:
# determinan = 0
np.linalg.det(K)

In [ ]:
# singular matrix, determinan = 0
np.linalg.inv(K)

## **Tensor**

In [40]:
M1 = np.array([[2, 5, 1],
               [2, 2, 2]])

M2 = np.array([[1, 3, 3],
               [5, 0, 1]])

M3 = np.array([[3, 1, 0],
               [0, 0, 1]])

M4 = np.array([[5, 0, 0],
               [1, 0, 1]])

In [41]:
tensor = np.array([M1, M2, M3, M4])
tensor

array([[[2, 5, 1],
        [2, 2, 2]],

       [[1, 3, 3],
        [5, 0, 1]],

       [[3, 1, 0],
        [0, 0, 1]],

       [[5, 0, 0],
        [1, 0, 1]]])

In [ ]:
tensor.shape

In [ ]:
import matplotlib.pyplot as plt

pict = plt.imread('/content/2-4.jpg')

In [ ]:
plt.imshow(pict)

In [ ]:
pict

In [ ]:
pict.shape

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])