## Latihan Numpy 


In [1]:
#Import Library
import numpy as np

In [22]:
# Perubahan dari List ke Array
# np.array()
a = [1,2,3,4]
b = np.array(a)
print(b, type(b))

c = np.array([4,2,3,1])
print(c,type(c))



[1 2 3 4] <class 'numpy.ndarray'>
[4 2 3 1] <class 'numpy.ndarray'>


In [26]:
# Membuat List menggunakan arrange
d = np.arange(1,11)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
# Membuat Array 2D
# Lihat seberapa banyak kurung siku di awal untuk menentukan jumlah dimensi
e = [
    [1,2,3,4],[5,6,7,8]
]
e = np.array(e)
print(e)

[[1 2 3 4]
 [5 6 7 8]]


In [36]:
f = [
    [[1,2,3,4],
     [5,6,7,8]],
     
     [[10,11,12,13],
      [14,16,17,18]]
    ]
f = np.array(f)
f.ndim

3

In [46]:
#Menentukan ukuran suatu array
#.shape
print(e)
# Shape dari e
print(e.shape)
print(f.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
(2, 2, 4)


In [48]:
#Menentukan jumlah total elemen suatu array
#.size
print(e.size)
print(f.size)

8
16


In [65]:
#Indexing & Slicing
print(b)
print(b[0:3])
print(b[0:])
print(b[0:4:2])
#Mengubah urutan array 1D dari belakang ke depan (Descending)



[1 2 3 4]
[1 2 3]
[1 2 3 4]
[1 3]


**NOMOR 1**

Buatlah sebuah array seperti dibawah ini dan tambahkan setiap elemennya dengan `1`.

```
a = [10, 20, 30, 40, 50]
```

In [ ]:
#Cara 1 : Menambahkan dengan bil. skalar


In [ ]:
# Cara 2 : Menambahkan dengan "Special Array"
#np.ones()



**NOMOR 2**

Buatlah sebuah array seperti dibawah ini dan keluarkan element yang bernilai negatif.

```
b = [-3, 0, -2, 1, 2, 3, -4]
```

In [ ]:
#Buat array


In [ ]:
# Jika `b < 0` maka hanya akan dilakukan pengecekan apakah element di `b` kurang dari 0 atau tidak


In [ ]:
# Jika `b[b < 0]` maka element di `b` kurang dari 0 akan ditampilkan



**NOMOR 3**

Buatlah sebuah array seperti dibawah ini. Keluarkan element yang bernilai positif kemudian urutkan dari nilai yang kecil ke besar

```
c = [10, -8, 4, 5, -41, 7, 5, -4]
```

In [ ]:
#Buat array



In [ ]:
# Sort elemen dari bilangan kecil ke besar
#np.sort(nama_array)



In [ ]:
# Sort elemen dari bilangan besar ke kecil
#sort dan Slicing dengan step = -1



**NOMOR 4**

Buatlah array seperti dibawah ini kemudian tumpukkan secara horizontal dan vertikal satu sama lain.

```
d = [1, 2, 3, 4, 5]
e = [6, 7, 8, 9, 10]
```

In [ ]:
#Buat array


In [ ]:
#Stacking Horizontal -> np.hstack((array1,array2))
#Stacking Vertikal -> np.vstack((array1,array2))



**NOMOR 5**

Buatlah dua buah array seperti dibawah ini yang berasal dari 1 deklarasi variabel yang sama. Kemudian, kalikan array pertama dengan `2` dan kalikan array kedua dengan `3`.

```
f = [10, 20, 30, 40, 50]
```

Ekspektasi output : 
```
hasil perkalian dengan 2 -> [20, 40, 60, 80, 100] 
hasil perkalian dengan 3 -> [30, 60, 90, 120, 150]
```

In [ ]:
#Buat array f



In [ ]:
#Copy array f ke variabel baru


In [ ]:
#Kalikan masing2 variabel



**NOMOR 6**

Buatlah sebuah array seperti dibawah ini dan hitung total jumlahnya.

```
h = [1, 2, 3, 4, 5]
j = [ [1, 2, 3],
      [4, 5, 6]]
```

Ekspektasi output :

```
total nilai h = 15
total nilai j berdasarkan penjumlahan baris = [6, 15]
total nilai j berdasarkan penjumlahan kolom = [5, 7, 9]
```

In [ ]:
#Buat array



In [ ]:
#jumlahkan array h
#.sum()



In [ ]:
#Penjumlahan berdasarkan baris
#baris -> axis = 1



In [ ]:
#Penjumlahan berdasarkan kolom
# kolom -> axis = 0




**NOMOR 7**

Buatlah sebuah array seperti dibawah ini dan cari nilai `min`, `max`, dan `sum` per baris dan per kolom.

```
k = [ [1, 2, 3],
      [4, 5, 6]]
```

In [ ]:
#Buat array


In [ ]:
#Mencari nilai minimum -> .min()
#Mencari nilai maximum - > .max()
#Mencari nilai total -> .sum()




**NOMOR 8**

Buatlah sebuah array seperti dibawah ini dan cari baris kedua dan kolom kedua.

```
n = [ [1, 2, 3], 
      [4, 5, 6],
      [7, 8, 9]]
```

In [ ]:
#Buat array




In [ ]:
#Get baris&Kolom
# nama_array[baris,kolom]


In [ ]:
# Get baris kedua
# Bisa menggunakan n[1] atau n[1, :]



In [ ]:
# Get kolom kedua (menampilkan secara array 1D)
# nama_array[:, [index_kolom]]



In [ ]:
# Get elemen diagonal (dari kiri ke kanan)
# np.diag()
# buka dokumentasi




In [ ]:
# Get elemen diagonal (dari kanan ke kiri)
# np.diag(np.fliplr(n))



**NOMOR 9**

Buatlah sebuah array seperti dibawah ini dan cari nilai `min`, `max`, dan `sum` untuk baris kedua dan kolom kedua.

```
m = [ [1, 2, 3], 
      [4, 5, 6],
      [7, 8, 9]]
```

In [ ]:
#Buat array



In [ ]:
#buat variabel yang berisikan baris ke 2


#buat variabel yang berisikan kolom ke 2



In [ ]:
#Cari masing2 nilai sum, min, dan max




**NOMOR 10**

<img src='https://i.ibb.co/JvBzgWn/greyscale.png'>

Download image [disini](https://i.ibb.co/JvBzgWn/greyscale.png)

* Load gambar tersebut dengan menggunakan library matplotlib.
* Jawab pertanyaan berikut ini : 
  - Berapa ukuran gambar tersebut.
  - Berapa total piksel/element pada gambar tersebut.
  - Cerahkan gambar tersebut dengan menambahkan suatu angka.

In [ ]:
#Install matplotlib in jupyter
import sys  
!{sys.executable} -m pip install --user matplotlib

In [ ]:
#Import matplotlib
import matplotlib.pyplot as plt

In [ ]:
#Baca gambar menggunakan plt.imread('location_gambar') lalu masukkan ke variabel



In [ ]:
#Cek ukuran gambar
#.shape



In [ ]:
# Total Piksel
#.size


In [ ]:
#Nilai piksel
#img, udah di scalling



In [ ]:
#Memastikan tipe data menjadi array
#np.asarray()




In [ ]:
#Menentukan nilai yg akan ditambahkan ke piksel
#Ubah ke skala 0-1, divide by 255 (highest pixel value)




In [ ]:
#Copy datanya dulu (penting setiap ingin memodifikasi data) ke variabel baru

#tambahkan nilai piksel ke gambar



In [ ]:
# Menampilkan gambar original
# `img` : array gambar
# `cmap` : color map #figure
# `vmin` : value minimum #figure
# `vmax` : value maximum #figure
#plt.imshow(nama_variabel, cmap='gray', vmin=0, vmax=1)



In [ ]:
# Menampilkan gambar yg sudah ditambah suatu value

